[package]
name = "grassfinder"
version = "0.1.0"
authors = ["polymetric <polymetricofficial@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spiral = "0.1"

[profile.release]
lto = true
